version: '2'
services:
  auction-web:
    image: nginx:1.11.8-alpine
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - auction-fpm
    ports:
      - "8080:80"
    links:
      - auction-fpm
  auction-db:
    image: mysql:5.7.17
    environment:
      - MYSQL_DATABASE=auction
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "3306:3306"
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
  auction-fpm:
    build: .
    environment:
      - AUCTION_DSN=mysql://root@auction-db:3306/auction
      - AUCTION_DEBUG=1
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor
    links:
      - auction-db
